services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market-parser-bot
    ports:
      - 8000:8000
    volumes:
    - ./src:/src
    - ./tests:/tests
    entrypoint:
      -python

  api:
    image: market-parser-bot
    depends_on:
      - postgres
    environment:
      - DB_HOST=${POSTGRES_PASSWORD:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432